#!/usr/bin/env python3
"""
ADL Consultancy static build.

Assembles src/partials/ + src/pages/ into:

  dist/          the deliverable. One file per page, body markup only — no
                 header, no footer, because those are their own files:
                 dist/header.html and dist/footer.html. Shared CSS and JS sit
                 alongside as _shared-styles.css and _shared-scripts.js.
  dist/preview/  the same pages with header and footer assembled in, purely so
                 they can be opened in a browser for review. Never hand off
                 these files — they would give you two headers on a site that
                 already has a global one.

Edit src/. Never edit dist/ — it is regenerated and overwritten.

Usage:  python3 build.py
"""

import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "src"
PARTIALS = SRC / "partials"
PAGES = SRC / "pages"
DIST = ROOT / "dist"
PREVIEW = DIST / "preview"

STAMP = "<!-- GENERATED by build.py — edit src/, not this file -->"

META_RE = re.compile(r"^<!--meta\s*(.*?)-->\s*", re.S)
URL_RE = re.compile(r"\{\{url:([a-z0-9-]+)\}\}")
IMG_RE = re.compile(r"\{\{img:([^}]+)\}\}")

ASSETS = ROOT / "assets" / "img"

# ADL migrated from WordPress to Squarespace in September 2026, taking every
# /wp-content/uploads/ URL down with it. Images are therefore vendored into
# assets/img/ rather than hotlinked. For the paste tree they need a real base
# URL on whatever platform the site ends up on — set it here once the images
# have been uploaded, then rebuild.
WP_ASSET_BASE = "/assets/img/"


def read(path: Path) -> str:
    if not path.exists():
        sys.exit(f"ERROR: missing required file {path.relative_to(ROOT)}")
    return path.read_text(encoding="utf-8")


def parse_page(path: Path) -> dict:
    """Split a page file into its <!--meta ... --> block and its body markup."""
    raw = read(path)
    match = META_RE.match(raw)
    if not match:
        sys.exit(f"ERROR: {path.name} has no <!--meta ... --> block at the top")

    meta = {}
    for line in match.group(1).strip().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if ":" not in line:
            sys.exit(f"ERROR: {path.name} meta line is not 'key: value' -> {line!r}")
        key, value = line.split(":", 1)
        meta[key.strip()] = value.strip()

    for required in ("key", "out", "wp", "title", "description"):
        if required not in meta:
            sys.exit(f"ERROR: {path.name} meta is missing '{required}'")

    meta["body"] = raw[match.end():].strip()
    meta["src"] = path.name
    return meta


def resolve_urls(html: str, pages: list, mode: str) -> str:
    """Rewrite {{url:key}} and {{img:file}} for the target tree."""
    lookup = {p["key"]: (p["out"] if mode == "preview" else p["wp"]) for p in pages}

    def swap_url(match):
        key = match.group(1)
        if key not in lookup:
            sys.exit(f"ERROR: unknown page key in {{{{url:{key}}}}} — no src/pages/*.html declares it")
        return lookup[key]

    def swap_img(match):
        name = match.group(1)
        if not (ASSETS / name).exists():
            sys.exit(f"ERROR: {{{{img:{name}}}}} has no file at assets/img/{name}")
        if mode == "preview":
            return "../assets/img/" + name      # preview lives one level down
        return WP_ASSET_BASE + name             # deliverable: live site path

    return IMG_RE.sub(swap_img, URL_RE.sub(swap_url, html))


def build():
    shell = read(PARTIALS / "shell.html")
    header = read(PARTIALS / "header.html")
    footer = read(PARTIALS / "footer.html")
    styles = read(PARTIALS / "styles.css")
    scripts = read(PARTIALS / "scripts.js")
    icons = read(PARTIALS / "icons.html")
    shell = shell.replace("{{SCRIPTS}}", scripts)

    page_files = sorted(PAGES.glob("*.html"))
    if not page_files:
        sys.exit("ERROR: no pages found in src/pages/")
    pages = [parse_page(p) for p in page_files]

    keys = [p["key"] for p in pages]
    if len(keys) != len(set(keys)):
        dupes = {k for k in keys if keys.count(k) > 1}
        sys.exit(f"ERROR: duplicate page key(s): {', '.join(sorted(dupes))}")

    DIST.mkdir(exist_ok=True)
    PREVIEW.mkdir(parents=True, exist_ok=True)
    for stale in list(DIST.glob("*.html")) + list(PREVIEW.glob("*.html")):
        stale.unlink()

    # vendored images, so the preview opens correctly straight from disk
    dist_assets = DIST / "assets" / "img"
    dist_assets.mkdir(parents=True, exist_ok=True)
    copied = 0
    for img in sorted(ASSETS.iterdir()):
        if img.is_file():
            shutil.copy2(img, dist_assets / img.name)
            copied += 1

    written = 0

    for page in pages:
        # ---- the deliverable: body markup only, no header, no footer --------
        body = resolve_urls(page["body"], pages, "live").replace("{{PAGEKEY}}", page["key"])
        (DIST / page["out"]).write_text(
            f"{STAMP}\n"
            f"<!-- {page['title']} -->\n"
            f"<!-- Page content only. The header and footer are separate files:\n"
            f"     header.html and footer.html. Shared CSS/JS: _shared-styles.css,\n"
            f"     _shared-scripts.js. Target URL: {page['wp']} -->\n"
            f'<div class="adl-page" id="adl-main" data-page="{page["key"]}">\n{body}\n</div>\n',
            encoding="utf-8",
        )

        # ---- preview only: same page with header and footer assembled in ----
        html = (
            shell.replace("{{STYLES}}", styles)
            .replace("{{HEADER}}", icons + "\n" + header)
            .replace("{{FOOTER}}", footer)
            .replace("{{BODY}}", page["body"])
            .replace("{{TITLE}}", page["title"])
            .replace("{{DESCRIPTION}}", page["description"])
            .replace("{{PAGEKEY}}", page["key"])
        )
        html = resolve_urls(html, pages, "preview")
        (PREVIEW / page["out"]).write_text(
            f"{STAMP}\n<!-- PREVIEW ONLY — do not hand this file off, it contains "
            f"the header and footer. The deliverable is ../{page['out']} -->\n{html}\n",
            encoding="utf-8",
        )
        written += 1

    # ---- header and footer, each its own file ------------------------------
    for name, fragment in (("header", header), ("footer", footer)):
        frag = resolve_urls(fragment, pages, "live").replace("{{PAGEKEY}}", "")
        (DIST / f"{name}.html").write_text(
            f"{STAMP}\n<!-- ADL site {name}. Goes in the platform's global {name}, "
            f"once, site-wide. Not in the page files. -->\n"
            f'<div class="adl-page">\n{frag}\n</div>\n',
            encoding="utf-8",
        )

        preview_frag = resolve_urls(fragment, pages, "preview").replace("{{PAGEKEY}}", "")
        standalone = (
            shell.replace("{{STYLES}}", styles)
            .replace("{{HEADER}}", icons + "\n" + (preview_frag if name == "header" else ""))
            .replace("{{FOOTER}}", preview_frag if name == "footer" else "")
            .replace(
                "{{BODY}}",
                f'<section class="wrap" style="padding:80px 0">'
                f"<h1>ADL {name}</h1>"
                f'<p class="lede">Standalone preview of the {name}. '
                f"The file to hand off is dist/{name}.html.</p></section>",
            )
            .replace("{{TITLE}}", f"ADL {name} — preview")
            .replace("{{DESCRIPTION}}", f"Standalone preview of the ADL {name}.")
            .replace("{{PAGEKEY}}", name)
        )
        (PREVIEW / f"{name}.html").write_text(f"{STAMP}\n{standalone}\n", encoding="utf-8")

    # ---- shared stylesheet + script, added once site-wide ------------------
    (DIST / "_shared-styles.css").write_text(
        "/* GENERATED by build.py — edit src/partials/styles.css, not this file.\n"
        "   Add once, site-wide (a Custom CSS box, or an enqueued stylesheet).\n"
        "   Every rule is scoped under .adl-page so it cannot collide with the theme. */\n\n"
        + styles,
        encoding="utf-8",
    )
    (DIST / "_icons.html").write_text(
        f"{STAMP}\n" + icons,
        encoding="utf-8",
    )
    (DIST / "_shared-scripts.js").write_text(
        "/* GENERATED by build.py — edit src/partials/scripts.js, not this file.\n"
        "   Add once, site-wide. Every feature it powers degrades gracefully:\n"
        "   with this file absent the site is still fully readable and navigable. */\n\n"
        + scripts,
        encoding="utf-8",
    )

    # ---- report ------------------------------------------------------------
    placeholders = sum(p["body"].count("adl-placeholder") for p in pages)
    print(f"  {written} page files (body only, no header/footer)  ->  dist/")
    print("  header.html + footer.html (their own files)      ->  dist/")
    print("  _icons.html + _shared-styles.css + _shared-scripts.js  ->  dist/")
    print(f"  {written + 2} assembled pages (review only)              ->  dist/preview/")
    print(f"  {copied} vendored images                              ->  dist/assets/img/")
    if placeholders:
        print(f"  {placeholders} placeholder block(s) still in the build")
    print("Done.")


if __name__ == "__main__":
    build()
