#!/usr/bin/env python3
"""
ADL Consultancy static build.

Assembles src/partials/ + src/pages/ into two output trees:

  dist/      standalone HTML — open any file in a browser, header and footer
             are baked in. This is the client preview.
  dist/wp/   paste payloads for WordPress/Avada, where the header and footer
             are global and the stylesheet lives in Custom CSS, so each page
             file carries body markup only.

Edit src/. Never edit dist/ — it is regenerated and overwritten.

Usage:  python3 build.py
"""

import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "src"
PARTIALS = SRC / "partials"
PAGES = SRC / "pages"
DIST = ROOT / "dist"
DIST_WP = DIST / "wp"

STAMP = "<!-- GENERATED by build.py — edit src/, not this file -->"

META_RE = re.compile(r"^<!--meta\s*(.*?)-->\s*", re.S)
URL_RE = re.compile(r"\{\{url:([a-z0-9-]+)\}\}")
IMG_RE = re.compile(r"\{\{img:([^}]+)\}\}")

ASSETS = ROOT / "assets" / "img"

# ADL migrated from WordPress to Squarespace in September 2026, taking every
# /wp-content/uploads/ URL down with it. Images are therefore vendored into
# assets/img/ rather than hotlinked. For the paste tree they need a real base
# URL on whatever platform the site ends up on — set it here once the images
# have been uploaded, then rebuild.
WP_ASSET_BASE = "/assets/img/"


def read(path: Path) -> str:
    if not path.exists():
        sys.exit(f"ERROR: missing required file {path.relative_to(ROOT)}")
    return path.read_text(encoding="utf-8")


def parse_page(path: Path) -> dict:
    """Split a page file into its <!--meta ... --> block and its body markup."""
    raw = read(path)
    match = META_RE.match(raw)
    if not match:
        sys.exit(f"ERROR: {path.name} has no <!--meta ... --> block at the top")

    meta = {}
    for line in match.group(1).strip().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if ":" not in line:
            sys.exit(f"ERROR: {path.name} meta line is not 'key: value' -> {line!r}")
        key, value = line.split(":", 1)
        meta[key.strip()] = value.strip()

    for required in ("key", "out", "wp", "title", "description"):
        if required not in meta:
            sys.exit(f"ERROR: {path.name} meta is missing '{required}'")

    meta["body"] = raw[match.end():].strip()
    meta["src"] = path.name
    return meta


def resolve_urls(html: str, pages: list, mode: str) -> str:
    """Rewrite {{url:key}} and {{img:file}} for the target tree."""
    lookup = {p["key"]: (p["out"] if mode == "dist" else p["wp"]) for p in pages}

    def swap_url(match):
        key = match.group(1)
        if key not in lookup:
            sys.exit(f"ERROR: unknown page key in {{{{url:{key}}}}} — no src/pages/*.html declares it")
        return lookup[key]

    def swap_img(match):
        name = match.group(1)
        if not (ASSETS / name).exists():
            sys.exit(f"ERROR: {{{{img:{name}}}}} has no file at assets/img/{name}")
        return ("assets/img/" + name) if mode == "dist" else (WP_ASSET_BASE + name)

    return IMG_RE.sub(swap_img, URL_RE.sub(swap_url, html))


def build():
    shell = read(PARTIALS / "shell.html")
    header = read(PARTIALS / "header.html")
    footer = read(PARTIALS / "footer.html")
    styles = read(PARTIALS / "styles.css")
    scripts = read(PARTIALS / "scripts.js")
    shell = shell.replace("{{SCRIPTS}}", scripts)

    page_files = sorted(PAGES.glob("*.html"))
    if not page_files:
        sys.exit("ERROR: no pages found in src/pages/")
    pages = [parse_page(p) for p in page_files]

    keys = [p["key"] for p in pages]
    if len(keys) != len(set(keys)):
        dupes = {k for k in keys if keys.count(k) > 1}
        sys.exit(f"ERROR: duplicate page key(s): {', '.join(sorted(dupes))}")

    DIST.mkdir(exist_ok=True)
    DIST_WP.mkdir(parents=True, exist_ok=True)
    for stale in list(DIST.glob("*.html")) + list(DIST_WP.glob("*.html")):
        stale.unlink()

    # vendored images, copied so dist/ opens correctly straight from disk
    dist_assets = DIST / "assets" / "img"
    dist_assets.mkdir(parents=True, exist_ok=True)
    copied = 0
    for img in sorted(ASSETS.iterdir()):
        if img.is_file():
            shutil.copy2(img, dist_assets / img.name)
            copied += 1

    written = 0

    for page in pages:
        # ---- standalone preview -------------------------------------------
        html = (
            shell.replace("{{STYLES}}", styles)
            .replace("{{HEADER}}", header)
            .replace("{{FOOTER}}", footer)
            .replace("{{BODY}}", page["body"])
            .replace("{{TITLE}}", page["title"])
            .replace("{{DESCRIPTION}}", page["description"])
            .replace("{{PAGEKEY}}", page["key"])
        )
        html = resolve_urls(html, pages, "dist")
        (DIST / page["out"]).write_text(f"{STAMP}\n{html}\n", encoding="utf-8")

        # ---- WordPress body-only payload ----------------------------------
        wp_body = resolve_urls(page["body"], pages, "wp")
        wp_body = wp_body.replace("{{PAGEKEY}}", page["key"])
        (DIST_WP / page["out"]).write_text(
            f"{STAMP}\n"
            f"<!-- {page['title']} — paste into the WordPress page at {page['wp']} -->\n"
            f'<div class="adl-page" data-page="{page["key"]}">\n{wp_body}\n</div>\n',
            encoding="utf-8",
        )
        written += 1

    # ---- header / footer as their own deliverables -------------------------
    for name, fragment, note in (
        ("header", header, "Avada → Global Header (or theme header.php)"),
        ("footer", footer, "Avada → Global Footer (or theme footer.php)"),
    ):
        wp_fragment = resolve_urls(fragment, pages, "wp").replace("{{PAGEKEY}}", "")
        (DIST_WP / f"{name}.html").write_text(
            f"{STAMP}\n<!-- ADL {name} — paste into {note} -->\n"
            f'<div class="adl-page">\n{wp_fragment}\n</div>\n',
            encoding="utf-8",
        )

        preview = resolve_urls(fragment, pages, "dist").replace("{{PAGEKEY}}", "")
        standalone = (
            shell.replace("{{STYLES}}", styles)
            .replace("{{HEADER}}", preview if name == "header" else "")
            .replace("{{FOOTER}}", preview if name == "footer" else "")
            .replace(
                "{{BODY}}",
                f'<section class="wrap" style="padding:80px 0">'
                f"<h1>ADL {name}</h1>"
                f"<p class=\"lede\">Standalone preview of the {name}. "
                f"The paste-ready version is dist/wp/{name}.html.</p></section>",
            )
            .replace("{{TITLE}}", f"ADL {name} — preview")
            .replace("{{DESCRIPTION}}", f"Standalone preview of the ADL {name}.")
            .replace("{{PAGEKEY}}", name)
        )
        (DIST / f"{name}.html").write_text(f"{STAMP}\n{standalone}\n", encoding="utf-8")

    # ---- shared stylesheet + script, pasted once into Avada ----------------
    (DIST_WP / "_shared-styles.css").write_text(
        "/* GENERATED by build.py — edit src/partials/styles.css, not this file.\n"
        "   Paste once into Avada → Theme Options → Custom CSS.\n"
        "   Every rule is scoped under .adl-page so it cannot collide with the theme. */\n\n"
        + styles,
        encoding="utf-8",
    )
    (DIST_WP / "_shared-scripts.js").write_text(
        "/* GENERATED by build.py — edit src/partials/scripts.js, not this file.\n"
        "   Enqueue once, site-wide. Every feature it powers degrades gracefully:\n"
        "   with this file absent the site is still fully readable and navigable. */\n\n"
        + scripts,
        encoding="utf-8",
    )

    # ---- report ------------------------------------------------------------
    placeholders = sum(p["body"].count("adl-placeholder") for p in pages)
    print(f"  {written} pages  ->  dist/  and  dist/wp/")
    print("  header.html + footer.html  ->  both trees")
    print("  _shared-styles.css + _shared-scripts.js  ->  dist/wp/")
    print(f"  {copied} vendored images  ->  dist/assets/img/")
    if placeholders:
        print(f"  {placeholders} placeholder block(s) still in the build")
    print("Done.")


if __name__ == "__main__":
    build()
