#!/usr/bin/env python3
"""
Package the build for Squarespace 7.1 (Fluid Engine).

Produces dist/squarespace/, which is four things to paste and one file per page.
Run it after build.py.

Why the pieces land where they do:

  Code Injection > HEADER  writes into <head>. Stylesheets belong there; markup
                           put there does not render at all.
  Code Injection > FOOTER  writes just before </body>. That is the only place a
                           site-wide custom header and footer CAN live, so the
                           header markup goes there and CSS fixes it to the top.
  Design > Custom CSS      hides Squarespace's own header and footer, and opens
                           the Fluid Engine grid so our full-bleed sections can
                           reach the edge of the screen.
  A Code Block per page    the page body. No <script> in any of them: scripts in
                           a Fluid Engine code block add phantom height to the
                           block, so all JS goes in the Footer injection instead.
"""

import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DIST = ROOT / "dist"
OUT = DIST / "squarespace"
PAGES_OUT = OUT / "pages"

read = lambda p: p.read_text(encoding="utf-8")
STAMP = "<!-- GENERATED by sqs_build.py — edit src/, not this file -->"

# The section our code block sits in. The client sets this id in Squarespace
# (Edit section > ... > Section ID) so the CSS below can target only our section
# and leave the rest of the site alone.
SECTION_ID = "adl-section"


def build():
    if not (DIST / "header.html").exists():
        raise SystemExit("ERROR: run `python3 build.py` first")

    OUT.mkdir(parents=True, exist_ok=True)
    PAGES_OUT.mkdir(exist_ok=True)

    styles = read(DIST / "_shared-styles.css")
    scripts = read(DIST / "_shared-scripts.js")
    icons = read(DIST / "_icons.html")
    header = read(DIST / "header.html")
    footer = read(DIST / "footer.html")

    # ---- 1. HEAD: the stylesheet ------------------------------------------
    (OUT / "1-code-injection-HEADER.html").write_text(f"""{STAMP}
<!-- ===========================================================================
     PASTE INTO:  Settings > Advanced > Code Injection > HEADER
     Paste the whole of this file, including the <style> tags.
     This is the site's stylesheet. It loads in <head>, which is where a
     stylesheet has to be. Do not put any visible markup in this field — the
     HEADER field writes into <head> and markup there will not render.
     ======================================================================== -->
<style>
{styles}
</style>
""", encoding="utf-8")

    # ---- 2. BODY END: sprite + header + footer + scripts -------------------
    (OUT / "2-code-injection-FOOTER.html").write_text(f"""{STAMP}
<!-- ===========================================================================
     PASTE INTO:  Settings > Advanced > Code Injection > FOOTER
     Paste the whole of this file.

     This field writes just before </body>, so it is where the site header and
     footer markup must live. The CSS in file 3 pins the header to the top of
     the screen; the footer is last in the document already, which is correct.

     It also carries the icon sprite (every icon on the site points at it) and
     the site's JavaScript. The JavaScript is here, once, rather than inside the
     page code blocks, because scripts inside a Fluid Engine code block add
     phantom height to the block.
     ======================================================================== -->

<!-- icon sprite — every page references these; without it all icons render blank -->
{icons}

<!-- site header -->
{header}

<!-- site footer -->
{footer}

<script>
{scripts}
</script>
""", encoding="utf-8")

    # ---- 3. Custom CSS: hide native chrome, open the Fluid Engine grid -----
    (OUT / "3-custom-css.css").write_text(f"""/* {STAMP.strip('<!- >')}
   ===========================================================================
   PASTE INTO:  Design > Custom CSS
   ===========================================================================
   Three jobs: hide Squarespace's header and footer so ours can replace them,
   pin our header to the top, and let our full-bleed sections reach the edge of
   the screen instead of being trapped inside the Fluid Engine gutter.
   ======================================================================== */

/* ---- 1. hide Squarespace's own header and footer ----------------------- */
/* Ours replaces both. If you ever want Squarespace's back, delete this block. */
#header,
.header,
#footer-sections,
.sqs-announcement-bar-dropzone {{
  display: none !important;
}}

/* ---- 2. pin our header ------------------------------------------------- */
/* It is injected at the end of <body>, so it needs taking out of flow and
   putting at the top. The hero reserves space for it already. */
.adl-header {{
  position: fixed !important;
  top: 0; left: 0; right: 0;
  margin-bottom: 0 !important;
}}

/* ---- 3. let our sections go edge to edge ------------------------------- */
/* Fluid Engine writes its layout as inline styles, and an inline style is only
   beaten by !important — hence the !important here. Scoped to our own section
   id so the rest of the site is untouched. */
#{SECTION_ID} .fluid-engine {{
  --sqs-site-max-width: 100vw;
  --sqs-site-gutter: 0vw;
  --sqs-mobile-site-gutter: 0vw;
}}
#{SECTION_ID} .sqs-block,
#{SECTION_ID} .sqs-block-code,
#{SECTION_ID} .sqs-block-content {{
  padding: 0 !important;
  margin: 0 !important;
  max-width: none !important;
}}
#{SECTION_ID} .page-section,
#{SECTION_ID} .content-wrapper,
#{SECTION_ID} .section-border {{
  padding-left: 0 !important;
  padding-right: 0 !important;
  max-width: none !important;
}}

/* ---- 4. Squarespace adds its own vertical padding to every section ------ */
/* Ours already has its own, so the two stack up into a large empty gap. */
#{SECTION_ID} {{
  padding-top: 0 !important;
  padding-bottom: 0 !important;
}}

/* ---- 5. belt and braces against sideways scroll ------------------------ */
/* Squarespace is prone to it, and a full-bleed hero is the usual culprit. */
body {{
  overflow-x: hidden;
}}
""", encoding="utf-8")

    # ---- 4. one file per page ---------------------------------------------
    count = 0
    for page in sorted(DIST.glob("*.html")):
        if page.name.startswith("_") or page.name in ("header.html", "footer.html"):
            continue
        body = read(page)
        # Strip the build's own comment header; the client pastes the markup.
        body = re.sub(r"^<!--.*?-->\s*", "", body, flags=re.S)
        assert "<script" not in body.lower(), f"{page.name} contains a script"
        (PAGES_OUT / page.name).write_text(f"""<!-- {page.stem} — paste into a Code Block on this page.
     Squarespace: add a section, add a Code Block, paste everything below.
     Then set the section's id to "{SECTION_ID}" (Edit section > ... > Section ID)
     so the Custom CSS can let it run edge to edge. -->
{body}""", encoding="utf-8")
        count += 1

    write_install(count)
    print(f"  4 paste files + {count} page files -> dist/squarespace/")


def write_install(count):
    (OUT / "INSTALL.md").write_text(f"""# Putting this on Squarespace 7.1

Do these in order. Steps 1–3 are done once for the whole site; step 4 is per page.

You need a **Core plan or above** — JavaScript in code blocks and Code Injection
are premium features. The dropdown, mobile menu, standards tabs and video
lightbox all need JavaScript.

---

## 1. The stylesheet

**Settings ▸ Advanced ▸ Code Injection ▸ HEADER**

Paste the whole of `1-code-injection-HEADER.html`, `<style>` tags included.

That field writes into `<head>`, which is where a stylesheet belongs. Do not put
any visible markup in it — markup in `<head>` does not render.

## 2. The header, footer, icons and scripts

**Settings ▸ Advanced ▸ Code Injection ▸ FOOTER**

Paste the whole of `2-code-injection-FOOTER.html`.

That field writes just before `</body>`, which is the only place a site-wide
custom header and footer can live. Step 3 pins the header to the top.

The icon sprite is in this file too. **Without it every icon on the site renders
blank** — there are over 300 references to it.

## 3. Hide Squarespace's header and footer

**Design ▸ Custom CSS**

Paste the whole of `3-custom-css.css`.

This hides Squarespace's own header and footer (ours replaces both), pins our
header, and opens the Fluid Engine grid so full-bleed sections reach the screen
edge.

## 4. Each page

{count} pages, one file each, in `pages/`.

For each one:

1. Create the page in Squarespace.
2. Add a section, then add a **Code Block** to it.
3. Paste the matching file from `pages/` into the code block.
4. **Set the section's ID to `{SECTION_ID}`** — Edit section ▸ ⋯ ▸ Section ID.
   Without this the section keeps Squarespace's gutter and nothing goes
   edge to edge.
5. Stretch the code block to the full width of the grid (drag its handles, or
   press `G` to show the grid).

## 5. Upload the images

All 31 are in `dist/assets/img/`. Upload them, then find and replace
`/assets/img/` in the pasted pages with whatever URL Squarespace gives them.
Until you do, every image on the site is a broken icon.

---

## Things that will bite you

- **Don't paste any `<script>` into a page code block.** A script inside a Fluid
  Engine code block makes the block taller than its content and leaves a gap.
  All the JavaScript is already in step 2.
- **Fluid Engine writes its layout as inline styles**, and an inline style can
  only be beaten by `!important`. That is why the Custom CSS uses it. Keep the
  `#{SECTION_ID}` scoping so the rest of the site is unaffected.
- **Upgrading a section to Fluid Engine cannot be undone**, and it changes the
  section's id. If a section stops going edge to edge after an edit, re-check
  its Section ID first.
- **The links between pages still use the old WordPress URLs** and will 404.
  Once the pages exist in Squarespace, send us the new URLs and we will remap
  them, or find and replace them yourself in the pasted markup.

## Checking it worked

On a phone, or a narrow browser window:

- The header shows the logo, a blue phone button and a hamburger.
- Tapping the phone button starts a call — this is the main thing people do.
- Opening the menu shows the standards with their code chips, and **both** the
  "Contact us" and "01279 293007" buttons are visible at the bottom without
  scrolling.
- Nothing scrolls sideways on any page.
- Icons are visible, not blank. If they are all blank, step 2 did not save.
""", encoding="utf-8")


if __name__ == "__main__":
    build()
